GET http://localhost:3003/api/blogs

####
POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRlc3RpIiwiaWQiOiI2MzBjOGY0YzU4MGRkNDZjMWJmNTk1MjAiLCJpYXQiOjE2NjE3NzgyNDR9.dcd-qtgHs4n2tuad0RY_5FTtORBH11C2RqW0lgtPidM

{
    "title": "Uudestaan",
    "author": "kimmo kirjoittaja",
    "url": "https://www.mielenkiintoista-a.fi/osa-2/",
    "likes": 2
}

###
DELETE http://localhost:3003/api/blogs/630c7f5448a8f71bb4029cc4
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRlc3RpIiwiaWQiOiI2MzBjOGY0YzU4MGRkNDZjMWJmNTk1MjAiLCJpYXQiOjE2NjE3NzgyNDR9.dcd-qtgHs4n2tuad0RY_5FTtORBH11C2RqW0lgtPidM


####

PUT http://localhost:3003/api/blogs/630c72fc81537dd4289495c9
content-type: application/json

{
    "likes": 2
}

### USER API TESTING
POST http://localhost:3003/api/users
content-type: application/json

{
    "username": "testaaja",
    "name": "jani testaa",
    "password": "12345"
}
###

GET http://localhost:3003/api/users

### LOGIN
POST http://localhost:3003/api/login
Content-Type: application/json

{
    "username": "testaaja",
    "password": "12345"
}